//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeStore2.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Threading.Tasks;
    using Persistence.Interfaces;
    public partial class FakeStore2Entities : DbContext, IFakeStore2Entities
    {
        public FakeStore2Entities()
            : base("name=FakeStore2Entities")
        {
        }

        //overwrites SaveChanges() from DbContext
        //it doesnt override anything, I just had to implement this so I could add this method to the interface
        public override int SaveChanges() => base.SaveChanges();

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Costumer> Costumers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
